---
- name: Generate Self-Signed Certificate
  command: openssl req -new -nodes -x509 -subj "/C=CA/ST=BC/L=Vancouver/O=TELUS/CN={{ ssl_certificate_common_name }}" -days 3650 -keyout {{ ssl_certificate_path_private }} -out {{ ssl_certificate_path_public }} -extensions v3_ca
  args:
    creates: "{{ ssl_certificate_path_public }}"
  when: ssl_certificate_self_signed

- name: Upload Public Certificate
  template:
    src: template.certificate
    dest: "{{ ssl_certificate_path_public }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: ssl_certificate_contents

- name: Upload Private Key
  template:
    src: template.key
    dest: "{{ ssl_certificate_path_private }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: ssl_certificate_contents
